name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.0']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Install dependencies
      run: gem build *.gemspec

    - uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: ./*.gem
    #- name: Publish to RubyGems
     # run: |
     #   mkdir -p $HOME/.gem
     #   touch $HOME/.gem/credentials
     #   chmod 0600 $HOME/.gem/credentials
     #   printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
     #   gem build *.gemspec
     #   gem push *.gem
     # env:
     #   GEM_HOST_API_KEY: "${{secrets.RUBY_SAMPLE_SECRET}}"
